/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DatePickerCalendarPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_view = require("@codemirror/view");
var DatePickerCalendarPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.calendarPopup = null;
    this.currentDateMatch = null;
  }
  async onload() {
    console.log("Loading Date Picker Calendar Plugin");
    this.registerEditorExtension(this.createDateCursorExtension());
    this.registerDomEvent(document, "click", (evt) => {
      if (this.calendarPopup && !this.calendarPopup.contains(evt.target)) {
        this.closeCalendar();
      }
    });
  }
  onunload() {
    this.closeCalendar();
  }
  createDateCursorExtension() {
    const plugin = this;
    let checkTimeout = null;
    return import_view.EditorView.updateListener.of((update) => {
      if (update.selectionSet) {
        if (checkTimeout) {
          clearTimeout(checkTimeout);
        }
        checkTimeout = setTimeout(() => {
          const view = update.view;
          const selection = view.state.selection.main;
          const cursorPos = selection.head;
          const line = view.state.doc.lineAt(cursorPos);
          const lineText = line.text;
          const lineNumber = line.number - 1;
          const dateRegex = /📅\s*(\d{4}-\d{2}-\d{2})/g;
          let match;
          let found = false;
          while ((match = dateRegex.exec(lineText)) !== null) {
            const matchStart = line.from + match.index;
            const matchEnd = matchStart + match[0].length;
            if (cursorPos >= matchStart && cursorPos <= matchEnd) {
              const coords = view.coordsAtPos(matchStart);
              if (coords) {
                const dateStr = match[1];
                plugin.showCalendar(
                  { left: coords.left, top: coords.top, bottom: coords.bottom },
                  {
                    dateStr,
                    startCh: match.index,
                    endCh: match.index + match[0].length,
                    line: lineNumber
                  }
                );
                found = true;
              }
              break;
            }
          }
          if (!found) {
            plugin.closeCalendar();
          }
        }, 100);
      }
    });
  }
  showCalendar(position, dateMatch) {
    this.closeCalendar();
    this.currentDateMatch = dateMatch;
    const calendar = this.createCalendarElement(dateMatch.dateStr);
    document.body.appendChild(calendar);
    this.calendarPopup = calendar;
    const rect = calendar.getBoundingClientRect();
    let left = position.left;
    let top = position.bottom + 5;
    if (left + rect.width > window.innerWidth) {
      left = window.innerWidth - rect.width - 10;
    }
    if (top + rect.height > window.innerHeight) {
      top = position.top - rect.height - 5;
    }
    calendar.style.left = `${left}px`;
    calendar.style.top = `${top}px`;
  }
  createCalendarElement(dateStr) {
    const container = document.createElement("div");
    container.className = "date-picker-calendar-popup";
    const currentDate = dateStr ? new Date(dateStr) : new Date();
    let viewYear = currentDate.getFullYear();
    let viewMonth = currentDate.getMonth();
    const render = () => {
      container.innerHTML = "";
      const shortcuts = container.createDiv({ cls: "calendar-shortcuts" });
      const shortcutItems = [
        { label: "\u4ECA\u5929", offset: 0 },
        { label: "\u660E\u5929", offset: 1 },
        { label: "2\u5929\u540E", offset: 2 },
        { label: "3\u5929\u540E", offset: 3 },
        { label: "1\u5468\u540E", offset: 7 }
      ];
      shortcutItems.forEach((item) => {
        const btn = shortcuts.createEl("div", {
          text: item.label,
          cls: "calendar-shortcut-btn"
        });
        btn.addEventListener("click", (e) => {
          e.stopPropagation();
          const date = new Date();
          date.setDate(date.getDate() + item.offset);
          this.selectDate(this.formatDate(date));
        });
      });
      const clearBtn = shortcuts.createEl("div", {
        text: "\u6E05\u9664",
        cls: "calendar-shortcut-btn calendar-clear-btn"
      });
      clearBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.clearDate();
      });
      const calendarMain = container.createDiv({ cls: "calendar-main" });
      const header = calendarMain.createDiv({ cls: "calendar-header" });
      const prevBtn = header.createEl("button", { text: "\u2039", cls: "calendar-nav-btn" });
      prevBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        viewMonth--;
        if (viewMonth < 0) {
          viewMonth = 11;
          viewYear--;
        }
        render();
      });
      const monthYearLabel = header.createEl("div", {
        text: `${viewYear}\u5E74${viewMonth + 1}\u6708`,
        cls: "calendar-month-year"
      });
      const nextBtn = header.createEl("button", { text: "\u203A", cls: "calendar-nav-btn" });
      nextBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        viewMonth++;
        if (viewMonth > 11) {
          viewMonth = 0;
          viewYear++;
        }
        render();
      });
      const weekHeader = calendarMain.createDiv({ cls: "calendar-week-header" });
      const weekDays = ["\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D", "\u65E5"];
      weekDays.forEach((day) => {
        weekHeader.createEl("div", { text: day, cls: "calendar-weekday" });
      });
      const grid = calendarMain.createDiv({ cls: "calendar-grid" });
      const firstDay = new Date(viewYear, viewMonth, 1);
      const lastDay = new Date(viewYear, viewMonth + 1, 0);
      let startDayOfWeek = firstDay.getDay() - 1;
      if (startDayOfWeek === -1)
        startDayOfWeek = 6;
      const daysInMonth = lastDay.getDate();
      const prevMonthLastDay = new Date(viewYear, viewMonth, 0).getDate();
      for (let i = startDayOfWeek - 1; i >= 0; i--) {
        const day = prevMonthLastDay - i;
        grid.createEl("div", {
          text: day.toString(),
          cls: "calendar-day calendar-day-other-month"
        });
      }
      for (let day = 1; day <= daysInMonth; day++) {
        const dayEl = grid.createEl("div", {
          text: day.toString(),
          cls: "calendar-day"
        });
        const cellDate = new Date(viewYear, viewMonth, day);
        const cellDateStr = this.formatDate(cellDate);
        if (cellDateStr === dateStr) {
          dayEl.addClass("calendar-day-selected");
        }
        const today = new Date();
        if (cellDate.toDateString() === today.toDateString()) {
          dayEl.addClass("calendar-day-today");
        }
        dayEl.addEventListener("click", (e) => {
          e.stopPropagation();
          this.selectDate(cellDateStr);
        });
      }
      const totalCells = startDayOfWeek + daysInMonth;
      const remainingCells = 42 - totalCells;
      for (let i = 1; i <= remainingCells && totalCells + i <= 42; i++) {
        grid.createEl("div", {
          text: i.toString(),
          cls: "calendar-day calendar-day-other-month"
        });
      }
    };
    render();
    return container;
  }
  selectDate(dateStr) {
    if (!this.currentDateMatch)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view)
      return;
    const editor = view.editor;
    const { line, startCh, endCh } = this.currentDateMatch;
    editor.replaceRange(
      `\u{1F4C5} ${dateStr}`,
      { line, ch: startCh },
      { line, ch: endCh }
    );
    this.closeCalendar();
  }
  clearDate() {
    if (!this.currentDateMatch)
      return;
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view)
      return;
    const editor = view.editor;
    const { line, startCh, endCh } = this.currentDateMatch;
    editor.replaceRange(
      "",
      { line, ch: startCh },
      { line, ch: endCh }
    );
    this.closeCalendar();
  }
  closeCalendar() {
    if (this.calendarPopup) {
      this.calendarPopup.remove();
      this.calendarPopup = null;
    }
    this.currentDateMatch = null;
  }
  formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
};
